### PR TITLE
Fixed gma files don't support relative parent folders + Improved messages

### PR DESCRIPTION
**Pull request by Xalalau**
https://wiki.facepunch.com/gmod/Global.include

The workshop version is broken.

### CODE REVIEW

**Comment by Xalalau** [comment]
Improved messages:

Before:

[DOWNLOADER] STARTING TO ADD RESOURCES FOR 83 ADDONS...
[DOWNLOADER] ADDING RESOURCE FOR 'Nuke Pack 4' WITH WSID '106565409'
[DOWNLOADER] ADDING RESOURCE FOR 'Parakeet's Pill Pack' WITH WSID '950845673'
[DOWNLOADER] ADDING RESOURCE FOR 'Minecraft Pill Pack' WITH WSID '325599907'
[DOWNLOADER] ADDING RESOURCE FOR 'Half-Life DM Source Pill Pack' WITH WSID '304514750'
[DOWNLOADER] ADDING RESOURCE FOR 'Extinguishing Water' WITH WSID '1228296128'
[DOWNLOADER] ADDING RESOURCE FOR 'Spawn Beds' WITH WSID '2011992051'
[DOWNLOADER] ADDING RESOURCE FOR 'Orbital Friendship Cannon' WITH WSID '124648402'
[DOWNLOADER] ADDING RESOURCE FOR 'Ultimate Drugs' WITH WSID '853257424'
[DOWNLOADER] ADDING RESOURCE FOR 'VJ Base' WITH WSID '131759821'
[DOWNLOADER] ADDING RESOURCE FOR 'Schwarz's CS 1.6 SWEPS (REUPLOADED)' WITH WSID '600841219'
[DOWNLOADER] ADDING RESOURCE FOR 'SCars Slim' WITH WSID '104483020'
[DOWNLOADER] ADDING RESOURCE FOR 'Mario Kart Wii - Medium SCars n' Props' WITH WSID '536420054'
[DOWNLOADER] ADDING RESOURCE FOR 'Volkswagen Beetle Scar' WITH WSID '180710326'
[DOWNLOADER] ADDING RESOURCE FOR 'Red's '67 Bus - SCar' WITH WSID '1234489469'
[DOWNLOADER] ADDING RESOURCE FOR 'Red's '31 Model A - SCar' WITH WSID '727990350'
[DOWNLOADER] ADDING RESOURCE FOR '[VJ Base] Crab SNPC' WITH WSID '1472038503'
[DOWNLOADER] ADDING RESOURCE FOR '[VJ Base] Terminal 7 SNPCs' WITH WSID '1349848320'
[DOWNLOADER] ADDING RESOURCE FOR 'HL2 vehicles with guns' WITH WSID '104503988'
[DOWNLOADER] ADDING RESOURCE FOR 'Greenscreen Material [Reupload]' WITH WSID '104635769'
[DOWNLOADER] ADDING RESOURCE FOR 'PAC3' WITH WSID '104691717'
[DOWNLOADER] ADDING RESOURCE FOR 'SmartSnap' WITH WSID '104815552'
[DOWNLOADER] ADDING RESOURCE FOR 'Star Wars Lightsabers' WITH WSID '111412589'
[DOWNLOADER] ADDING RESOURCE FOR 'Dollynho v2' WITH WSID '585815778'
[DOWNLOADER] ADDING RESOURCE FOR 'Comidas Br' WITH WSID '540241537'
[DOWNLOADER] ADDING RESOURCE FOR 'Rag Morph' WITH WSID '104509899'
[DOWNLOADER] ADDING RESOURCE FOR 'Outfitter: Multiplayer player models' WITH WSID '882463775'
[DOWNLOADER] ADDING RESOURCE FOR 'Wowozela' WITH WSID '108170491'
[DOWNLOADER] ADDING RESOURCE FOR 'Wiremod' WITH WSID '160250458'
[DOWNLOADER] ADDING RESOURCE FOR 'PlayX' WITH WSID '106516163'
[DOWNLOADER] ADDING RESOURCE FOR 'DIDI - Pão - Renato Aragão' WITH WSID '306267352'
[DOWNLOADER] ADDING RESOURCE FOR 'Faustão' WITH WSID '297867947'
[DOWNLOADER] FINISHED TO ADD RESOURCES
[38;5;9m[DOWNLOADER] POINTSHOP 1 NOT FOUND

After:

[DOWNLOADER] SCANNING 83 ADDONS TO ADD RESOURCES...
[DOWNLOADER] [+] (106565409) Nuke Pack 4
[DOWNLOADER] [+] (950845673) Parakeet's Pill Pack
[DOWNLOADER] [+] (325599907) Minecraft Pill Pack
[DOWNLOADER] [+] (304514750) Half-Life DM Source Pill Pack
[DOWNLOADER] [+] (1228296128) Extinguishing Water
[DOWNLOADER] [+] (2011992051) Spawn Beds
[DOWNLOADER] [+] (124648402) Orbital Friendship Cannon
[DOWNLOADER] [+] (853257424) Ultimate Drugs
[DOWNLOADER] [+] (131759821) VJ Base
[DOWNLOADER] [+] (600841219) Schwarz's CS 1.6 SWEPS (REUPLOADED)
[DOWNLOADER] [+] (104483020) SCars Slim
[DOWNLOADER] [+] (536420054) Mario Kart Wii - Medium SCars n' Props
[DOWNLOADER] [+] (180710326) Volkswagen Beetle Scar
[DOWNLOADER] [+] (1234489469) Red's '67 Bus - SCar
[DOWNLOADER] [+] (727990350) Red's '31 Model A - SCar
[DOWNLOADER] [+] (1472038503) [VJ Base] Crab SNPC
[DOWNLOADER] [+] (1349848320) [VJ Base] Terminal 7 SNPCs
[DOWNLOADER] [+] (104503988) HL2 vehicles with guns
[DOWNLOADER] [+] (104635769) Greenscreen Material [Reupload]
[DOWNLOADER] [+] (104691717) PAC3
[DOWNLOADER] [+] (104815552) SmartSnap
[DOWNLOADER] [+] (111412589) Star Wars Lightsabers
[DOWNLOADER] [+] (585815778) Dollynho v2
[DOWNLOADER] [+] (540241537) Comidas Br
[DOWNLOADER] [+] (104509899) Rag Morph
[DOWNLOADER] [+] (882463775) Outfitter: Multiplayer player models
[DOWNLOADER] [+] (108170491) Wowozela
[DOWNLOADER] [+] (160250458) Wiremod
[DOWNLOADER] [+] (106516163) PlayX
[DOWNLOADER] [+] (306267352) DIDI - Pão - Renato Aragão
[DOWNLOADER] [+] (297867947) Faustão
[DOWNLOADER] FINISHED TO ADD RESOURCES: 31 ADDONS SELECTED
[38;5;9m[DOWNLOADER] POINTSHOP 1 NOT FOUND, SKIPPING PLAYERMODELS CHECK

**Comment by Xalalau** [comment]
What about this ugly [38;5;9m? Anyway,

**Comment by Xalalau** [comment]
Improved messages:

Before:
```
[DOWNLOADER] STARTING TO ADD RESOURCES FOR 83 ADDONS...
[DOWNLOADER] ADDING RESOURCE FOR 'Nuke Pack 4' WITH WSID '106565409'
[DOWNLOADER] ADDING RESOURCE FOR 'Parakeet's Pill Pack' WITH WSID '950845673'
[DOWNLOADER] ADDING RESOURCE FOR 'Minecraft Pill Pack' WITH WSID '325599907'
[DOWNLOADER] ADDING RESOURCE FOR 'Half-Life DM Source Pill Pack' WITH WSID '304514750'
[DOWNLOADER] ADDING RESOURCE FOR 'Extinguishing Water' WITH WSID '1228296128'
[DOWNLOADER] ADDING RESOURCE FOR 'Spawn Beds' WITH WSID '2011992051'
[DOWNLOADER] ADDING RESOURCE FOR 'Orbital Friendship Cannon' WITH WSID '124648402'
[DOWNLOADER] ADDING RESOURCE FOR 'Ultimate Drugs' WITH WSID '853257424'
[DOWNLOADER] ADDING RESOURCE FOR 'VJ Base' WITH WSID '131759821'
[DOWNLOADER] ADDING RESOURCE FOR 'Schwarz's CS 1.6 SWEPS (REUPLOADED)' WITH WSID '600841219'
[DOWNLOADER] ADDING RESOURCE FOR 'SCars Slim' WITH WSID '104483020'
[DOWNLOADER] ADDING RESOURCE FOR 'Mario Kart Wii - Medium SCars n' Props' WITH WSID '536420054'
[DOWNLOADER] ADDING RESOURCE FOR 'Volkswagen Beetle Scar' WITH WSID '180710326'
[DOWNLOADER] ADDING RESOURCE FOR 'Red's '67 Bus - SCar' WITH WSID '1234489469'
[DOWNLOADER] ADDING RESOURCE FOR 'Red's '31 Model A - SCar' WITH WSID '727990350'
[DOWNLOADER] ADDING RESOURCE FOR '[VJ Base] Crab SNPC' WITH WSID '1472038503'
[DOWNLOADER] ADDING RESOURCE FOR '[VJ Base] Terminal 7 SNPCs' WITH WSID '1349848320'
[DOWNLOADER] ADDING RESOURCE FOR 'HL2 vehicles with guns' WITH WSID '104503988'
[DOWNLOADER] ADDING RESOURCE FOR 'Greenscreen Material [Reupload]' WITH WSID '104635769'
[DOWNLOADER] ADDING RESOURCE FOR 'PAC3' WITH WSID '104691717'
[DOWNLOADER] ADDING RESOURCE FOR 'SmartSnap' WITH WSID '104815552'
[DOWNLOADER] ADDING RESOURCE FOR 'Star Wars Lightsabers' WITH WSID '111412589'
[DOWNLOADER] ADDING RESOURCE FOR 'Dollynho v2' WITH WSID '585815778'
[DOWNLOADER] ADDING RESOURCE FOR 'Comidas Br' WITH WSID '540241537'
[DOWNLOADER] ADDING RESOURCE FOR 'Rag Morph' WITH WSID '104509899'
[DOWNLOADER] ADDING RESOURCE FOR 'Outfitter: Multiplayer player models' WITH WSID '882463775'
[DOWNLOADER] ADDING RESOURCE FOR 'Wowozela' WITH WSID '108170491'
[DOWNLOADER] ADDING RESOURCE FOR 'Wiremod' WITH WSID '160250458'
[DOWNLOADER] ADDING RESOURCE FOR 'PlayX' WITH WSID '106516163'
[DOWNLOADER] ADDING RESOURCE FOR 'DIDI - Pão - Renato Aragão' WITH WSID '306267352'
[DOWNLOADER] ADDING RESOURCE FOR 'Faustão' WITH WSID '297867947'
[DOWNLOADER] FINISHED TO ADD RESOURCES
�[38;5;9m[DOWNLOADER] POINTSHOP 1 NOT FOUND
```

After:

```
[DOWNLOADER] SCANNING 83 ADDONS TO ADD RESOURCES...
[DOWNLOADER] [+] 106565409  Nuke Pack 4
[DOWNLOADER] [+] 950845673  Parakeet's Pill Pack
[DOWNLOADER] [+] 325599907  Minecraft Pill Pack
[DOWNLOADER] [+] 304514750  Half-Life DM Source Pill Pack
[DOWNLOADER] [+] 1228296128 Extinguishing Water
[DOWNLOADER] [+] 2011992051 Spawn Beds
[DOWNLOADER] [+] 124648402  Orbital Friendship Cannon
[DOWNLOADER] [+] 853257424  Ultimate Drugs
[DOWNLOADER] [+] 131759821  VJ Base
[DOWNLOADER] [+] 600841219  Schwarz's CS 1.6 SWEPS (REUPLOADED)
[DOWNLOADER] [+] 104483020  SCars Slim
[DOWNLOADER] [+] 536420054  Mario Kart Wii - Medium SCars n' Props
[DOWNLOADER] [+] 180710326  Volkswagen Beetle Scar
[DOWNLOADER] [+] 1234489469 Red's '67 Bus - SCar
[DOWNLOADER] [+] 727990350  Red's '31 Model A - SCar
[DOWNLOADER] [+] 1472038503 [VJ Base] Crab SNPC
[DOWNLOADER] [+] 1349848320 [VJ Base] Terminal 7 SNPCs
[DOWNLOADER] [+] 104503988  HL2 vehicles with guns
[DOWNLOADER] [+] 104635769  Greenscreen Material [Reupload]
[DOWNLOADER] [+] 104691717  PAC3
[DOWNLOADER] [+] 104815552  SmartSnap
[DOWNLOADER] [+] 111412589  Star Wars Lightsabers
[DOWNLOADER] [+] 585815778  Dollynho v2
[DOWNLOADER] [+] 540241537  Comidas Br
[DOWNLOADER] [+] 104509899  Rag Morph
[DOWNLOADER] [+] 882463775  Outfitter: Multiplayer player models
[DOWNLOADER] [+] 108170491  Wowozela
[DOWNLOADER] [+] 160250458  Wiremod
[DOWNLOADER] [+] 106516163  PlayX
[DOWNLOADER] [+] 306267352  DIDI - Pão - Renato Aragão
[DOWNLOADER] [+] 297867947  Faustão
[DOWNLOADER] FINISHED TO ADD RESOURCES: 31 ADDONS SELECTED
[38;5;9m[DOWNLOADER] POINTSHOP 1 NOT FOUND, SKIPPING PLAYERMODELS CHECK
```

What about this ugly [38;5;9m? Anyway.

**Comment by ceifa** [comment]
This ugly `[38;5;9m` it's a color. Windows CMD doesn't support it :(

**Pull request merged**
